CREATE TABLE IF NOT EXISTS USERS (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Password_Hash VARCHAR(255) NOT NULL,
    Role ENUM('RECRUITER', 'EMPLOYEE') DEFAULT 'RECRUITER',
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Resume_URL TEXT
);
CREATE TABLE IF NOT EXISTS JOBS (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Description TEXT NOT NULL,
    Company VARCHAR(255) NOT NULL,
    Location VARCHAR(255) NOT NULL,
    Salary DECIMAL(10, 2),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CreatedBy INT NOT NULL,
    FOREIGN KEY (CreatedBy) REFERENCES USERS(Id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS CANDIDATES (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Phone VARCHAR(20),
    Skills TEXT,
    Education TEXT,
    Experience_Years TEXT,
    Resume_URL TEXT,
    Resume_TEXT TEXT,
    Parsed_JSON JSON,
    Applied_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS APPLICATIONS (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    JobId INT NOT NULL,
    CandidateId INT NOT NULL,
    Status ENUM('APPLIED', 'REJECTED', 'INTERVIEWED', 'SHORTLISTED', 'HIRED') DEFAULT 'APPLIED',
    Notes TEXT,
    Updated_At DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Resume_URL TEXT,
    FOREIGN KEY (CandidateId) REFERENCES CANDIDATES(Id) ON DELETE CASCADE,
    FOREIGN KEY (JobId) REFERENCES JOBS(Id) ON DELETE CASCADE
);
